### ISSUE TITLE
[windows] python error

### ISSUE THREAD

**Issue by mi-ael** [lasote/conan-boost#1]
Hi,
I tried to use boost 1.59.0 with conan in my project, but the download was slow. I decided to download it from another mirror and replaced the other .zip file.

"conan install --build Boost" crashed in boosts conanfile.py in line 51:
```
self.run("cd %s && type bootstrap.log" if self.settings.os == "Windows" else "cd %s && cat bootstrap.sh")
```
It took me a few minutes before i realized that boost was never unpacked and that that line above should have given me a error message, if it hadn't crashed.

my conan.conf:
```

[storage]
# This is the default path, but you can write your own
path: G:/conan_data

[remotes]
conan.io: https://server.conan.io
local: http://localhost:9300

[settings_defaults]

arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
```

Thanks for the work your doing with conan and boost. I hope conan will make a platform independent boost setup more easy.

**Comment by lasote** [comment]
Hi! As I said in the other issue, thanks to you. I'm really happy with your help!.
You said that download was slow, What was slow? The boost zip download?  Where you changed the mirror? 
I suppose you finally were able to start the building, Then it crashes as you mentioned in #2 right?

**Comment by mi-ael** [comment]
> You said that download was slow, What was slow? The boost zip download?
Yes, i meant the boost zip download from Sourceforge.

> Where you changed the mirror?
I just downloaded the boost zip file via browser and replaced the file conan wanted to download.

```
self.run("cd %s && type bootstrap.log" if self.settings.os == "Windows" else "cd %s && cat bootstrap.sh")
```
I'm no python programmer, but this line looked like a syntax error.

**Comment by lasote** [comment]
Hi, I have fixed some errors and uploaded version 1.60 now without building dependencies and for a lot of compilers. Could you try it? If you still need the 1.59 should be working too.

**Comment by mi-ael** [comment]
1.60 is file, I'll try it out as soon AS possible

**Comment by mi-ael** [comment]
Everything works :+1: 

I still get some "Filename too long" errors for some documentation Files, but that's be
e "Filename too long" errors for some documentation Files, but that's because it is simply not possible to install boost with conan with a shorter path than "G:\conan_data\Boost\1.60.0\lasote\stable\build\b2fa7916a0f122b3fb8af1388c987d95c5729177\boost_1_60_0" and boost has paths like "boost_1_60_0/libs/geometry/doc/html/geometry/reference/spatial_indexes/boost__geometry__index__rtree/rtree_parameters_type_const____indexable_getter_const____value_equal_const____allocator_type_const___.html"

I look up the documentation on the boost website anyway when I need it.
